services:
  postgres:
    image: postgres:17-alpine
    container_name: reservation-db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: reservation_user
      POSTGRES_PASSWORD: reservation_pass
      POSTGRES_DB: reservation_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
